Revert "fanotify: fix false positive on permission events"
Because android12-5.10 skipped all the changes in v5.10.220, the struct fsnotify_iter_info is missing the current_group member.

../fs/notify/mark.c:360:34: error: no member named 'current_group' in 'struct fsnotify_iter_info'
                        if (mark->group == iter_info->current_group) {
                                           ~~~~~~~~~  ^

This reverts commit a24765332e129c1916d5a6615418b75599b8fcdc.

Change-Id: Id253dd85d3fee0c425598ad8d0e97679ee328642
Signed-off-by: vlxlxlv <fajarslebew31@gmail.com>